apiVersion: v2
name: program-director
description: AI-powered TV channel programmer for Tunarr
type: application
version: 1.1.0
appVersion: "1.0.3"
keywords:
  - media
  - automation
  - tunarr
  - plex
  - radarr
  - sonarr
maintainers:
  - name: geekxflood
    url: https://github.com/geekxflood/program-director
sources:
  - https://github.com/geekxflood/program-director
